version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    steps:
      - run: 
          name: install mysql client
          command: |
              sudo apt-get update
              sudo apt-get install -y mysql-client
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run: 
          name: show database in mysql
          command: mysql -h 127.0.0.1 -u user -ppassw0rd -e 'show databases;'
